config/routes.rb
Rails.application.routes.draw do
  root to: 'entries#index'

  resources :categories
  resources :entries

  resources :channels do
    get :refresh
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :channels, dependent: :nullify, inverse_of: :category
  has_many :entries, through: :channels
end

app/models/channel.rb
class Channel < ActiveRecord::Base
  belongs_to :category, inverse_of: :channels
  has_many :entries, inverse_of: :channel, dependent: :destroy

  scope :without_category, -> { where(category_id: nil) }
end

app/models/entry.rb
class Entry < ActiveRecord::Base
  belongs_to :channel, inverse_of: :entries
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  decent_configuration do
    strategy DecentExposure::StrongParametersStrategy
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  expose(:category, attributes: :category_params)

  def create
    if category.save
      redirect_to categories_path, notice: t('.success')
    else
      render :new
    end
  end

  def update
    if category.save
      redirect_to category, notice: t('.success')
    else
      render :edit
    end
  end

  def destroy
    category.destroy
    redirect_to :back, notice: t('.success')
  end

  private

  def category_params
    params.require(:category).permit(:title, :description)
  end
end

app/controllers/channels_controller.rb
class ChannelsController < ApplicationController
  expose(:channels)
  expose(:channel, attributes: :channel_params)

  def create
    channel = FetchChannel.call(params: channel_params).result

    if channel.save
      RefreshChannel.call(channel: channel)
      redirect_to channel, notice: t('.success')
    else
      render :new
    end
  end

  def update
    if channel.save
      redirect_to channel, notice: t('.success')
    else
      render :edit
    end
  end

  def refresh
    if RefreshChannel.call(channel: channel).result
      redirect_to channel, notice: t('.success')
    else
      redirect_to channel, error: t('.failure')
    end
  end

  def destroy
    channel.destroy
    redirect_to categories_path, notice: t('.success')
  end

  private

  def channel_params
    params.require(:channel).permit(:title, :description, :site_url, :feed_url, :category_id)
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  expose(:entries)
  expose(:entry)

  def destroy
    if entry.update(status: :read)
      render json: { status: 200 }
    else
      render json: { status: 420 }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def categories
    Category.all
  end
end

app/helpers/channels_helper.rb
module ChannelsHelper
  def channels_without_category
    Channel.without_category
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/categories/_category.slim
h3= header

- if channels.empty?
  .empty-state
    div This category is empty
- else
  ul
    - channels.each do |channel|
      li= link_to channel.title, channel  

app/views/categories/_form.slim
.form
  = simple_form_for category do |f|
    = f.input :title
    = f.input :description
    = f.submit

app/views/categories/edit.slim
header
  h2= 'Edit category'

.content
  = render 'form'

app/views/categories/index.slim
header
  h2= 'Settings'
  
  .actions
    = link_to 'new category', new_category_path, class: 'button create'
    = link_to 'new channel', new_channel_path, class: 'button create' 
    
.content
  .group-listing
    .group= render 'category', header: 'Uncategorized', channels: channels_without_category
  
    - categories.each do |category|
      .group
        = render 'category', header: category.title, channels: category.channels
      
        .settings
          = link_to 'Edit category', [:edit, category]
          = link_to 'Delete category', category, method: :delete, data: { confirm: 'Are you sure?' }

app/views/categories/new.slim
header
  h2= 'New category'

.content
  = render 'form'

app/views/channels/edit.slim
header
  h2= 'Edit channel'

.content
  .form
    = simple_form_for channel do |form|
      = form.input :feed_url, disabled: true
      = form.input :title
      = form.input :description
      = form.input :site_url
      = form.association :category
      = form.button :submit

app/views/channels/new.slim
header
  h2= 'New channel'

.content
  .form
    = simple_form_for channel do |form|
      = form.input :feed_url
      = form.association :category
      = form.button :submit

app/views/channels/show.slim
.entries
  header
    = link_to '', channel_refresh_path(channel), class: 'refresh'
    h2= channel.title
    
    .actions
      = link_to 'Edit', [:edit, channel], class: 'button update'
      = link_to 'Delete', channel, method: :delete, data: { confirm: 'Are you sure?' }, class: 'button destroy'

  section.content
    - channel.entries.each do |e|
      .entry
        .panel
          = link_to '', '#', class: 'bookmark'
          = link_to '', e, method: :delete, class: 'remove'
        .box
          section.title= link_to e.title, e
          section.bar
            section.left= e.author
            section.right= time_ago_in_words(e.published_at)
          section.body
            = e.summary
          
javascript:
  $(".entries .content").masonry({
    itemSelector: ".entry",
    isAnimated: true,
    animationOptions: {
      duration: 300,
      easing: 'linear',
      queue: false
    }
  });

app/views/entries/index.slim
.entries
  header
    h2= 'All'

  section.content
    - entries.each do |e|
      .entry
        .panel
          = link_to '', '#', class: 'bookmark'
          = link_to '', e, method: :delete, class: 'remove'
        .box
          section.title= link_to e.title, e
          section.bar
            section.left= e.author
            section.right= time_ago_in_words(e.published_at)
          section.body
            = e.summary

javascript:
  $(".entries .content").masonry({
    itemSelector: ".entry",
    isAnimated: true,
    animationOptions: {
      duration: 300,
      easing: 'linear',
      queue: false
    }
  });

app/views/entries/show.slim
.preview
  header
    h2= entry.title
    
    .actions
      = link_to '', entry.channel, class: 'backarrow'
       
  article.content
    = entry.content.html_safe

app/views/layouts/application.slim
doctype html
html
  head
    title Blackbird
    = stylesheet_link_tag   'http://fonts.googleapis.com/css?family=Open+Sans:400,300'
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    aside
      .sidebar
        .logo
        nav
          li.feeds= link_to '', entries_path
          li.settings= link_to '', categories_path

      .navigation.channels.column_list
        = render 'layouts/application/navigation'
    
    main
      = yield

app/views/layouts/application/_navigation.slim
= render 'layouts/application/navigation_entry', header: 'Uncategorized', channels: channels_without_category

- categories.each do |category|
  = render 'layouts/application/navigation_entry', header: category.title, channels: category.channels
  

app/views/layouts/application/_navigation_entry.slim
section
  .header
    = header
    
  ul
    - if channels.blank?
      i= 'No channels'
    - else
      - channels.each do |channel|
        li= link_to channel.title, channel, class: 'channel'